server:
  port: 9999
spring:
  datasource:
    username: root
    password: 1941915924
    url: jdbc:mysql://localhost:3306/xdb?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
  redis:
    port: 6379
    host: localhost
logging:
  level:
    com.system: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.system.*.entity